USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS care_wh
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = 'Warehouse for development and analysis database.';

SHOW WAREHOUSES;



