models:
  - name: dim_employer
    
    columns:
      - name: employer_id
        data_tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar

      - name: employer_name
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar

      - name: employer_workplace
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
      
      - name: employer_organization_number
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
      
      - name: workplace_street_address
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar

      - name: workplace_region
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar

      - name: workplace_postcode
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar

      - name: workplace_city
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar

      - name: workplace_country
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar




  - name: dim_job_details
    columns:
      - name: job_details_id
        data_tests:
          - not_null
          - unique
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar

      - name: headline
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar

      - name: description
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar

      - name: description_html_formatted
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar

      - name: employment_type
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ['Vanlig anställning', 'Behovsanställning', 'Sommaranställning / feriejobb', 'Type not specified']


      - name: duration
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ['6 månader eller längre', 'Tills vidare', 'Duration not specified', '3 månader – upp till 6 månader', '11 dagar - upp till 3 månader']
        
      - name: salary_type
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar

      - name: scope_of_work_min
        data_tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number

      - name: scope_of_work_max
        data_tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number

#Får fel, antagligen pga att dimensionsmodellen saknade denna columnen
      - name: occupation_label
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar

  - name: dim_auxiliary_attributes
    columns:
      - name: auxiliary_attributes_id
        data_tests:
         - not_null
         - unique
         - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar

      - name: experience_required
        data_tests:
         - not_null
         - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: boolean

      - name: driving_license_required
        data_tests:
         - not_null
         - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: boolean

      - name: access_to_own_car
        data_tests:
         - not_null
         - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: boolean



  - name: fct_job_ads
    columns:
      - name: job_ads_key
        data_tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar

      - name: job_details_key
        data_tests:
          - relationships:
              to: ref('dim_job_details')
              field: job_details_id
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          - not_null

      - name: employer_key
        data_tests:
          - relationships:
              to: ref('dim_employer')
              field: employer_id
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          - not_null

      - name: auxiliary_attributes_key
        data_tests:
          - relationships:
              to: ref('dim_auxiliary_attributes')
              field: auxiliary_attributes_id
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          - not_null

      - name: relevance
        data_tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0  
              max_value: 1 
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: float
          - not_null

      - name: vacancies
        data_tests: 
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 1
              max_value: 20          
          - dbt_expectations.expect_column_max_to_be_between:
              min_value: 1
              max_value: 20
              config:
                severity: warn
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
          - not_null

      - name: application_deadline
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: Timestamp_TZ
          - not_null

      - name: published_date
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: Timestamp_TZ
          - not_null
